# Example config file. Rename it to "config.yaml" and fill in the details.
# Provided values are defaults.
rpc_url: "https://columbus.camino.network/ext/bc/C/rpc"
booking_token_addr: "0xd4e2D76E656b5060F6f43317E8d89ea81eb5fF8D"
supplier_private_key: "<SUPPLIER PRIVATE KEY>"
buyer_private_key: "<BUYER PRIVATE KEY>"
abi_file: "abi/BookingTokenV0.abi"
